import ecep_cloud.ecep_wampServer.update_db
update_db.device_init()

import ecep_cloud.ecep_wampServer.container_control
import ecep_cloud.ecep_wampServer.wamp_server
import ecep_cloud.ecep_wampServer.request_handler